version: '3.9'
services:
  shell:
    build: ./docker   # docker directory Dockerfile
    #container_name: helloworld
    #restart: always
    tty: true
    # command: dos2unix /usr/src/helloworld.sh
    volumes:
      - ./shell:/usr/src:cached