FROM openjdk:8-jre-alpine
#RUN mkdir -p /opt/helloworld

ADD HelloWorld.class HelloWorld.class 
#ADD HelloWorld.class HelloWorld.class
#RUN apk --update add openjdk8-jre

ENTRYPOINT ["java","HelloWorld"]
