FROM ubuntu:18.04

#COPY ./iperf3_3.1.3-1_amd64.deb iperf3_3.1.3-1_amd64.deb
#COPY ./libiperf0_3.1.3-1_amd64.deb libiperf0_3.1.3-1_amd64.deb

# Timezone
#RUN dpkg -i iperf3_3.1.3-1_amd64.deb
#RUN dpkg -i libiperf0_3.1.3-1_amd64.deb

